// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhlghoieozjgqjxutndi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obGdob2llb3pqZ3FqeHV0bmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDg0MjcsImV4cCI6MjA2MzgyNDQyN30.IsQ8Dcoxg2K3JuT73nKiF-JphBagF_vKYZPov9p98Hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);